### ISSUE TITLE
I have not a single clue how to use your save editor.

### ISSUE THREAD

**Issue by raxele123** [araguma/holocure-save-editor#10]
Could you please make the instructions a bit more idiot friendly?

**Comment by araguma** [comment]
Sorry for the late reply. For some reason, GitHub didn't notify me about this issue. To get started with this repo and other similar repos in the future, you'll need to install Node.js which can be found [here](https://nodejs.org/en/download). After that, run `npm i holocure-save-editor` in a terminal which installs the 'holocure-save-editor' library into your current folder. You can then copy and paste the quick start code into an `index.js` file and then run `node index.js` to start it.

I'm no longer supporting this library, but feel free to contribute if you wish to add support for 0.6.
